server:
  port: 8080

spring:
  application:
    name: aws-lab-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
    properties:
     hibernate:
        temp:
          use_jdbc_metadata_defaults: false 
        format_sql: true
  logging:
    level:
      org.hibernate.orm.jdbc.bind: TRACE # SQL 파라미터 확인
      org.hibernate.SQL: DEBUG         # 실행 SQL 확인
      org.springframework.jdbc.datasource.DataSourceUtils: DEBUG # 연결 확인
